const express = require('express');
const app = express();
const config = require('./config/config.js');
var scrapper = require('./scraper');
var firebase = require('./firebaseDB');

app.listen(config.APP_PORT, function () {
    console.log('Successfully listening on port ' + config.APP_PORT);
    app.get('/', function (req, res) {
        res.sendfile(__dirname + '/mapper/getMap.html');
        console.log('Got a connection');
    });
    app.get('*', function (req, res) {
        //res.sendfile(__dirname + '/client/forohfour.html');
        //TODO create 404 html page
        res.send('Four oh four..');
        console.error('Invalid connection');
    })
});


// Upload the route encodings from the csv generated by running the python script
//firebase.updateRouteEncoding();

firebase.getRouteEncoding(function (encodings) {
    //console.log(encodings);
    encodedRouteIDs = Object.keys(encodings);
    //TODO move the calls here to a cyclic function every 30s
    encodedRouteIDs.forEach(function(v){
        scrapper.getBusSchedule(encodings[v], function (out) { // debug
            //console.log(JSON.stringify(out, null, 4)); // debug output
            firebase.updateRouteSchedule(v,out);
        });
    });
    console.log('Uploaded',encodedRouteIDs.length,'routes to Firebase');
});

//scrapper test and usage
// scrapper.getBusSchedule(1556, function (out) { // debug
//     console.log(JSON.stringify(out, null, 4)); // debug output
// });
